/**
 * Builds the `PluginRegistry` the app's `PipelineRunner` runs against:
 * registers `@topview/plugin-example-detector` as a built-in default
 * `FeatureDetector`, and wraps `@topview/svg-engine`'s plain export
 * functions into `plugin-sdk` `Exporter` plugin instances (svg-engine has
 * no `plugin-sdk` dependency of its own -- see docs/architecture.md -- so
 * this adapter layer is what bridges the two).
 *
 * Note the two packages each export an unrelated type named `ExportResult`:
 * schema/svg-engine's is `{ format, data, fileName, mimeType }` (the actual
 * bytes/string), while plugin-sdk's `Exporter.export()` contract requires
 * `{ format, output: DataRef }` (a *reference*, not inline bytes). This file
 * is exactly the seam that converts one into the other, wrapping the
 * generated bytes in a `blob:` URL so it satisfies `DataRef`.
 */
import {
  createPluginRegistry,
  SDK_VERSION,
  type DataRef,
  type Exporter,
  type ExportRequest,
  type ExportResult as PluginExportResult,
  type PluginManifest,
  type PluginRegistry,
} from '@topview/plugin-sdk';
import { detectedToProjectEntity } from '@topview/pipeline-core';
import {
  exportDxf,
  exportGeoJson,
  exportJson,
  exportObj,
  exportSvg,
  type ExportResult as SvgEngineExportResult,
} from '@topview/svg-engine';
import { EXAMPLE_WALL_DETECTOR_MANIFEST, ExampleWallDetector } from '@topview/plugin-example-detector';
import type { AnyEntity } from '@topview/schema';

function toProjectEntities(request: ExportRequest): AnyEntity[] {
  const layerId = 'layer-default';
  const entities: AnyEntity[] = [];
  for (const detected of request.scene.entities) {
    const projected = detectedToProjectEntity(detected, layerId);
    if (projected) entities.push(projected);
  }
  return entities;
}

function toDataRef(result: SvgEngineExportResult): DataRef {
  const part = result.data instanceof Uint8Array ? (result.data as unknown as BlobPart) : result.data;
  const blob = new Blob([part], { type: result.mimeType });
  const uri = URL.createObjectURL(blob);
  return { id: result.fileName, uri, mimeType: result.mimeType, sizeBytes: blob.size };
}

function makeExporterAdapter(
  manifestId: string,
  formats: readonly string[],
  run: (entities: AnyEntity[], request: ExportRequest) => SvgEngineExportResult,
): { manifest: PluginManifest; instance: Exporter } {
  const manifest: PluginManifest = {
    id: manifestId,
    name: manifestId,
    version: '0.1.0',
    kind: 'exporter',
    sdkVersionRange: `^${SDK_VERSION}`,
    entryPoint: './index.js',
  };
  const instance: Exporter = {
    manifestId,
    formats,
    configure: () => {},
    async export(request: ExportRequest): Promise<PluginExportResult> {
      const result = run(toProjectEntities(request), request);
      return { format: result.format, output: toDataRef(result) };
    },
    async dispose() {},
  };
  return { manifest, instance };
}

export function createDefaultPluginRegistry(): PluginRegistry {
  const registry = createPluginRegistry(SDK_VERSION);

  registry.register(EXAMPLE_WALL_DETECTOR_MANIFEST, () => new ExampleWallDetector());

  const exporters = [
    makeExporterAdapter('topview.exporter.svg', ['svg'], (entities) => exportSvg(entities)),
    makeExporterAdapter('topview.exporter.json', ['json'], (entities) => exportJson(entities, { pretty: true })),
    makeExporterAdapter('topview.exporter.geojson', ['geojson'], (entities) => exportGeoJson(entities)),
    makeExporterAdapter('topview.exporter.dxf', ['dxf'], (entities) => exportDxf(entities)),
    makeExporterAdapter('topview.exporter.obj', ['obj'], (entities) => exportObj(entities)),
  ];
  for (const exporter of exporters) {
    registry.register(exporter.manifest, () => exporter.instance);
  }

  return registry;
}
